openapi: 3.0.0
info:
  title: Server API
  description: Swagger API of Server.
  version: 0.1

  contact:
  name: Carlos Pasquali
  email: carlos.pasquali.dev@gmail.com
  url: https://carlospasqualidev.vercel.app

variables:
  protocol:
    enum:
      - http
      - https
    default: http

servers:
  - url: '{protocol}://localhost:8080/api'
    description: Localhost API
    variables:
      protocol:
        enum:
          - http
          - https
        default: http

securityDefinitions:
  BasicAuth:
    type: basic
security:
  - BasicAuth: []

paths:
  /exemples/send:
    get:
      tags:
        - Notifications
      summary: Send notifications.
      description: Send notifications.

  /exemples/check/expireds:
    get:
      tags:
        - Notifications
      summary: check for expireds notifications.
      description: check for expireds notifications.
