image: node:18.16.1

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev

stages:
  - build
  - staging_deploy
  - production_deploy

build:
  stage: build
  script:
    - npm install typescript
    - npm run build
    - ls
  only:
    - develop
    - master

staging_deploy:
  environment: review/develop
  stage: staging_deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - develop

production_deploy:
  environment: production
  stage: production_deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
