// eslint-disable-next-line global-require
export const swaggerAutogen = require('swagger-autogen')();

export const outputFile = '../docs/swaggerDocs.json';
export const endpointsFiles = ['../api/routes.ts'];

export const doc = {
  info: {
    version: '1.0.0',
    title: 'My API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
    contact: {
      email: 'produto@adalovelace.com.br',
      name: 'Ada Lovelace',
    },
  },
  host: 'localhost:8080',
  basePath: '/api',
  schemes: ['http', 'https'],
  securitySchemes: {
    bearerAuth: {
      type: 'http',
      scheme: 'bearer',
      bearerFormat: 'JWT',
    },
  },
  tags: [
    {
      name: 'User',
      description: 'Endpoints',
    },
  ],
  securityDefinitions: {
    bearer: {
      type: 'apiKey',
      name: 'bearer',
      in: 'header',
      scheme: 'bearer',
      bearerFormat: 'JWT',
    },
  },
  definitions: {
    User: {
      name: 'Jhon Doe',
      age: 29,
      parents: {
        father: 'Simon Doe',
        mother: 'Marie Doe',
      },
      diplomas: [
        {
          school: 'XYZ University',
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: 'XYZ Company',
          },
        },
      ],
    },
    AddUser: {
      $name: 'Jhon Doe',
      $age: 29,
      about: '',
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc);
