// eslint-disable-next-line global-require
export const swaggerAutogen = require('swagger-autogen')();

export const outputFile = '../docs/swaggerDocs.json';
export const endpointsFiles = ['../api/routes.ts'];

export const doc = {
  info: {
    version: '1.0.0',
    title: 'My API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
    contact: {
      email: 'produto@adalovelace.com.br',
      name: 'Ada Lovelace',
    },
  },
  host: 'localhost:8080',
  basePath: '/api',
  schemes: ['http', 'https'],
  security: { bearerAuth: [] },
  components: {
    securitySchemes: {
      BearerAuth: {
        type: 'http',
        scheme: 'bearer',
      },
    },
  },
  securityDefinitions: {
    bearer: {
      type: 'apiKey',
      name: 'bearer',
      in: 'header',
      scheme: 'bearer',
      bearerFormat: 'JWT',
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc);
